### PR TITLE
feat: Added `Table.plot_histograms` to plot a histogram for each column in the table

### LINKED ISSUE #157: Create histogram for all columns in a `Table`
### Is your feature request related to a problem?

Currently, a histogram can only be created for one column at a time. It would be useful to create one plot that contains histograms for all columns in a `Table`.

### Desired solution

* Add a method `plot_histograms` (note the **s**) to the `Table` class
* The method should place the histogram for each column in a grid
* It should be clear which plot belongs to which column

seaborn should already have a method to create a grid. If that's not the case, matplotlib definitely has one.

### PR DESCRIPTION
**Pull request by Marsmaennchen221**
Closes #157.

### Summary of Changes

Added `Table.plot_histograms` to plot a histpogram for each column in the table
Changed xticks in `Column.plot_histogram` to match `Table.plot_histograms` (the first and last xtick labels are outside of the value range)

### CODE REVIEW

**Comment by lars-reimann** [comment]
## [🦙 MegaLinter](https://megalinter.io/6.22.1) status: ✅ [SUCCESS](https://github.com/Safe-DS/Stdlib/actions/runs/4830778022)

| Descriptor  |                                 Linter                                 |Files|Fixed|Errors|Elapsed time|
|-------------|------------------------------------------------------------------------|-----|----:|------|------------|
|✅ PYTHON    |[black](https://megalinter.io/6.22.1/descriptors/python_black)          |    2|    0|     0|0.96s       |
|✅ PYTHON    |[mypy](https://megalinter.io/6.22.1/descriptors/python_mypy)            |    2|     |     0|2.16s       |
|✅ PYTHON    |[ruff](https://megalinter.io/6.22.1/descriptors/python_ruff)            |    2|    0|     0|0.05s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/6.22.1/descriptors/repository_git_diff)|yes  |     |no    |0.03s       |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Stdlib/actions/runs/4830778022)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by lars-reimann** [comment]
It would be nice if you would also add a call to this to https://stdlib.safe-ds.com/en/latest/tutorials/data_visualization/ by editing this notebook: https://github.com/Safe-DS/Stdlib/blob/main/docs/tutorials/data_visualization.ipynb

**Comment by Marsmaennchen221** [comment]
histogram
Currently numerical data will have a wider range in x values than needed. We had an alternative method to remove the first and last xtick as it is not needed but this would remove the first and last label from categorical data. We are not sure how we can solve this problem. For now the output has the larger scope

**Comment by lars-reimann** [comment]
This was the commit that ignores a warning: https://github.com/Safe-DS/Stdlib/commit/3aad07ddcc0da42e1dab2eed49fc41433a876765

**Review by lars-reimann — APPROVED** [review]

**Pull request merged**
