### PR TITLE
feat: Improve error handling of TaggedTable

### LINKED ISSUE #150: Improve error handling of `TaggedTable`
### Is your feature request related to a problem?

In some cases, error handling is not ideal (see solution for details).

### Desired solution

* Validate inputs of a function as the first step
* Raise an appropriate exception with an appropriate message if issues are found
* Document in the docstring that the exception is raised and under which condition
* Test that the correct exception with the correct message is raised

### Possible alternatives (optional)

_No response_

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by jxnior01**
Closes #150 

### Summary of Changes

* feat: Validated inputs of functions
* feat: Raised appropriate exceptions with appropriate messages
* docs: Modified docs
* tests: Tested all exceptions

### CODE REVIEW

**Comment by Marsmaennchen221** [comment]
Do we really want to catch every error twice? We already have the logic in the `Table` methods so the logic stays the same. If we want to change the logic of one of the errors we would have to do this in both the `Table` and the `TaggedTable`. I would prefer to only write additional errors in `TaggedTable` if they only occur in the `TaggedTable` methods or if they differ from the `Table` error logic/messages

**Comment by jxnior01** [comment]
> Do we really want to catch every error twice? We already have the logic in the `Table` methods so the logic stays the same. If we want to change the logic of one of the errors we would have to do this in both the `Table` and the `TaggedTable`. I would prefer to only write additional errors in `TaggedTable` if they only occur in the `TaggedTable` methods or if they differ from the `Table` error logic/messages

That makes sense, it's not ideal. I'll revise my changes to include additional error handling where necessary.

**Comment by Marsmaennchen221** [comment]
@jxnior01 I removed additional errors that are being raised by the methods from the `Table` class

**Comment by jxnior01** [comment]
> @jxnior01 I removed additional errors that are being raised by the methods from the `Table` class

Thanks. That was helpful.

**Review by Marsmaennchen221 — APPROVED** [review]

**Comment by zzril** [comment]
Looks good to me, although I've spotted a few cases where we don't make use of the new "suggest columns" feature. Not sure what our criterion is about when to make use of that.

Can merge if you like.

**Pull request merged**
