### PR TITLE
test: `shuffle_rows` should work on `Table`s with multiple rows

### LINKED ISSUE #401: The test for `Table.shuffle_rows` does not test the expected behaviour
### Is your feature request related to a problem?

The test for `Table.shuffle_rows` does not test wether the rows are shuffled or not as the fiven Table contains only one row. It also tests wether the table and the result are the same after the rows are shuffled.

### Desired solution

Add a test case where the table contains more than one row. Ideally you test that with a given seed the expected order will be given (See the example in the docstrings of this method).
The test **should not** test that the table and the result are the same. They should be different after the rows are shuffled.

### Possible alternatives (optional)

_No response_

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by daniaHu**
Closes #401

### Summary of Changes

Test that `shuffle_rows` also works with a `Table` that contain multiple rows.

### CODE REVIEW

**Review by alex-senger — APPROVED** [review]

**Review by alex-senger — CHANGES_REQUESTED** [review]
Maybe try adding a `random_state` parameter to the `shuffle_rows` method and putting it into the `random_state` parameter of `_data.sample()`

**Comment by lars-reimann** [comment]
> Maybe try adding a `random_state` parameter to the `shuffle_rows` method and putting it into the `random_state` parameter of `_data.sample()`

I don't think having the `random_state` as a parameter on every method that could be randomized is the way to go (see discussion in #12). It would be possible to just pass a hard-coded `random_state` to `pandas.sample` (e.g. `42` as done in #430) for now to ensure the method is deterministic. But we also discussed last week that it would suffice to test that all rows of the original table are still there after shuffling.

**Review by alex-senger — APPROVED** [review]
[LGTM](https://lgtm.party/p/NQ6R7TF8/)

**Review by zzril — APPROVED** [review]

**Review by zzril — CHANGES_REQUESTED** [review]
From the PR description:

> Closes #401
> ### Summary of Changes
> 
> Added parameter to test with multiple rows, used np.random.seed to expect the behaviour of shuffle_rows and compared the shuffled table with the expected table

This needs to be updated as you didn't go for the solution using `np.random.seed` in the end.

**Review by zzril — APPROVED** [review]

**Pull request merged**
