### PR TITLE
feat: Getters for hyperparameters of Regression and Classification models

### LINKED ISSUE #260: Getters for hyperparameters of models
### Is your feature request related to a problem?

It's currently not possible to check the values of hyperparameters of a classifier or regressor using the public API. Since they can only be created by calling the constructor this is not a major issue, yet. However, in the future we might also add capabilities to load pre-trained models. Then the values of their hyperparameters are no longer obvious.

### Desired solution

For each hyperparameter of a classifier or regressor add a `@property` method (a getter). We do **NOT** want setters in order to maintain immutability. The name of the method should be the same as the name of the attribute with the leading underscore removed.

Example (AdaBoost):

```py
class AdaBoost(Classifier):
    def __init__(self, learning_rate: float = 1.0) -> None:
        # ...
        self._learning_rate = learning_rate

    @property
    def learning_rate(self) -> float:
        return self._learning_rate
```

### Possible alternatives (optional)

_No response_

### Screenshots (optional)

_No response_

### Additional Context (optional)

To test the getters, use them in the existing tests instead of directly accessing the internal attributes (i.e. replace `classifier._learning_rate` with `classifier.learning_rate`.

### PR DESCRIPTION
**Pull request by PhilipGutberlet**
Closes #260 .

### Summary of Changes

Added properties/getters for the hyperparameters of all Regression and Classification models.

### CODE REVIEW

**Comment by lars-reimann** [comment]
## [🦙 MegaLinter](https://megalinter.io/6.22.2) status: ❌ [ERROR](https://github.com/Safe-DS/Stdlib/actions/runs/4959846789)

| Descriptor  |                                 Linter                                 |Files|Fixed|                            Errors                            |Elapsed time|
|-------------|------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------|------------|
|✅ PYTHON    |[black](https://megalinter.io/6.22.2/descriptors/python_black)          |   22|    3|                                                             0|0.91s       |
|❌ PYTHON    |[mypy](https://megalinter.io/6.22.2/descriptors/python_mypy)            |   22|     |[6](https://github.com/Safe-DS/Stdlib/actions/runs/4959846789)|1.88s       |
|✅ PYTHON    |[ruff](https://megalinter.io/6.22.2/descriptors/python_ruff)            |   22|    3|                                                             0|0.05s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/6.22.2/descriptors/repository_git_diff)|yes  |     |no                                                            |0.03s       |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Stdlib/actions/runs/4959846789)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by zzril** [comment]
The `c` parameter for the `SupportVectorMachine` also needs a getter. (Both in `classification` and `regression`.)

**Comment by zzril** [comment]
The IDE complains about missing docstrings for the getter methods.

**Review by zzril — CHANGES_REQUESTED** [review]
The `c` parameter for the `SupportVectorMachine` also needs a getter. (Both in classification and regression.)

**Review by zzril — APPROVED** [review]

**Comment by PhilipGutberlet** [comment]
> The IDE complains about missing docstrings for the getter methods. (I think you can just copy and paste them from the init methods.)
> 
> May want to discuss this in a new issue, though. (Or possibly try to automate this in the `mkdocs` functionality.) So, we will not consider this as a requirement for accepting this PR.
 
Would be a new issue.

**Review by Marsmaennchen221 — APPROVED** [review]

**Pull request merged**
