### PR TITLE
feat: added invert_colors method

### PR DESCRIPTION
**Pull request by sibre28**
Closes #[282].

### Summary of Changes

added `invert_colors` method to `Image`
added tests

Co-authored-by: PhilipGutberlet <92990487+PhilipGutberlet@users.noreply.github.com>

### CODE REVIEW

**Comment by lars-reimann** [comment]
## [🦙 MegaLinter](https://megalinter.io/7.0.4) status: ✅ [SUCCESS](https://github.com/Safe-DS/Stdlib/actions/runs/5289973772)

| Descriptor  |                                Linter                                 |Files|Fixed|Errors|Elapsed time|
|-------------|-----------------------------------------------------------------------|-----|----:|------|------------|
|✅ PYTHON    |[black](https://megalinter.io/7.0.4/descriptors/python_black)          |    2|    0|     0|0.62s       |
|✅ PYTHON    |[mypy](https://megalinter.io/7.0.4/descriptors/python_mypy)            |    2|     |     0|1.81s       |
|✅ PYTHON    |[ruff](https://megalinter.io/7.0.4/descriptors/python_ruff)            |    2|    1|     0|0.02s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/7.0.4/descriptors/repository_git_diff)|yes  |     |no    |0.0s        |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Stdlib/actions/runs/5289973772)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by sibre28** [comment]
Change tests to use a deep copy method, as every test for images should have the same format

**Comment by sibre28** [comment]
TODO: Change tests to use a deep copy method, as every test for images should have the same format

**Review by daniaHu — APPROVED** [review]

**Pull request merged**
