### PR TITLE
feat: properties for width-height of image

### LINKED ISSUE #290: Properties for width/height of image
### Is your feature request related to a problem?

I'd like to know the dimensions of an image in pixels.

### Desired solution

* Add `@property` `width` that returns the width of the image in pixels.
* Add `@property` `height` that returns the height of the image in pixels.

### Possible alternatives (optional)

_No response_

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by jxnior01**
Closes #290

### Summary of Changes

* feat: Properties for width and height of an image should be returned in pixels.

### CODE REVIEW

**Comment by lars-reimann** [comment]
## [🦙 MegaLinter](https://megalinter.io/7.0.4) status: ✅ [SUCCESS](https://github.com/Safe-DS/Stdlib/actions/runs/5287457063)

| Descriptor  |                                Linter                                 |Files|Fixed|Errors|Elapsed time|
|-------------|-----------------------------------------------------------------------|-----|----:|------|------------|
|✅ PYTHON    |[black](https://megalinter.io/7.0.4/descriptors/python_black)          |    2|    1|     0|0.78s       |
|✅ PYTHON    |[mypy](https://megalinter.io/7.0.4/descriptors/python_mypy)            |    2|     |     0|2.04s       |
|✅ PYTHON    |[ruff](https://megalinter.io/7.0.4/descriptors/python_ruff)            |    2|    1|     0|0.03s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/7.0.4/descriptors/repository_git_diff)|yes  |     |no    |0.01s       |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Stdlib/actions/runs/5287457063)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Review by robmeth — APPROVED** [review]
looks good

**Review by robmeth — APPROVED** [review]
still fine

**Pull request merged**
